#include        "../types.h"
#include        "../x6502.h"
#include        "../fce.h"
#define INESPRIV
#include        "../ines.h"
#include        "../version.h"
#include        "../memory.h"
#include	"../sound.h"
#include	"../svga.h"
#include	"../state.h"
#define UNIFPRIV
#include	"../unif.h"
#include	"../cart.h"
#include	"../cheat.h"
